### ISSUE TITLE
Question about clock frequency

### ISSUE THREAD

**Issue by N0ury** [teliot/SBS_ESP#1]
Hi,
This is a question, not an issue.
I'd like to try this lib on an ESP32-S2 or ESP32-C3.
Do you know if the change about clock frequency reduction necessary in my case?
Thanks

**Comment by teliot** [comment]
The clock issue may have been fixed by now. Check arduino source code.

**Comment by N0ury** [comment]
I have checked, but sadly I don't understand what has been done, if the issue is really solved.
Here's the new code:
```
void Twi::setClock(unsigned int freq)
{
    if (freq < 1000)  // minimum freq 1000Hz to minimize slave timeouts and WDT resets
    {
        freq = 1000;
    }

    preferred_si2c_clock = freq;

#if F_CPU == FCPU80

    if (freq > 400000)
    {
        freq = 400000;
    }
    twi_dcount = (500000000 / freq);  // half-cycle period in ns
    twi_dcount
        = (1000 * (twi_dcount - 1120)) / 62500;  // (half cycle - overhead) / busywait loop time

#else

    if (freq > 800000)
    {
        freq = 800000;
    }
    twi_dcount = (500000000 / freq);  // half-cycle period in ns
    twi_dcount
        = (1000 * (twi_dcount - 560)) / 31250;  // (half cycle - overhead) / busywait loop time

#endif
}
```

Do you think this is sufficient?
In the doc they talk about 10 to 100KHz.

**Comment by teliot** [comment]
Looks solved

**Comment by N0ury** [comment]
Ok, thanks a lot.
I'm gonna try the code on a dead battery, and I'll do the same on the one I have ordered when it will arrive.
I close the issue.
